# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sounds good to me.
email: phil@jack.chat
description: > # this means to ignore newlines until "baseurl:"
  A tech and stuff blog ... but mostly tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://derkobe.github.io" # the base hostname & protocol for your site
twitter_username: DerKobe
github_username:  DerKobe

# Build settings
markdown: kramdown
exclude: [.bundle, bin, vendor]
