# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sounds Good To Me
email: phil@jack.chat
description: > # this means to ignore newlines until "baseurl:"
  Well met! My name is Philip Claren and I'm a developer, musician, and one of the founders of Talk About Jack (http://jack.chat).
  My daily work is mostly about Elixir/Phoenix, Ruby, CoffeeScript, and SCSS. In my non-existent spare time I'm a passionate Hearthstone player, and on rare occasions I build music with Propellerhead's Reason and my trusty drumset.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://derkobe.github.io" # the base hostname & protocol for your site
twitter_username: DerKobe
github_username:  DerKobe

# Build settings
markdown: kramdown
exclude: [.bundle, bin, vendor]
